### ISSUE TITLE
Home page Layout

### ISSUE THREAD

**Issue by LydiaVuj** [chingu-voyages/bears-project-8#25]
Web frame and design

**Comment by sammychris** [comment]
I thought the LoggedIn and Registration page should be with the home page?

**Comment by arielbk** [comment]
It could be a part of the home page but then there will also be instances where we want to redirect to the login page itself (like after registering), rather than the homepage with text.

It could also be a modal when accessed from within the page. If the browser itself goes to the login path then it could be a separate page.

**Comment by arielbk** [comment]
- The most important thing about this page is that it should be stupidly easy to register and login.

- It should explain what the app is. People should have a clear idea within a few seconds.

- Beyond this, it should be visually appealing, drawing people in. It could be a chance to practice a 'storytelling' kind of design.
