### ISSUE TITLE
User profile layout

### ISSUE THREAD

**Issue by LydiaVuj** [chingu-voyages/bears-project-8#27]
Web frame and design

**Comment by arielbk** [comment]
Here are some ideas for what we could have on the profile page:

- Profile picture, name and member since; like what we already have
- Username
 
- Friend connections — friends can hold each other accountable through the app
- Invite friends

- Number of logged habits across number of habits. E.g. *‘Logged a habit 57 times across 3 habits’*

- Top habit tags — the tags that are most common across the user’s habits. This can give an idea about what the user’s focuses are.

- Goals — the user could define some of their overall goals here. Maybe later these could be more integrated with habits (you could associate a habit with a particular goal, show a goal’s progress, things like that).

- Edit profile
- Delete account

**Comment by sammychris** [comment]
This is so amazing, I love it!

**Comment by arielbk** [comment]
Prototype: https://www.figma.com/proto/ZViL2CINxOOoouihBYNSVlVm/Profile?node-id=70%3A151&viewport=-881%2C-12%2C1&scaling=min-zoom
